### PR TITLE
Allow users to customize requests.Session

### PR DESCRIPTION
**Pull request by yugui**
For example, you can specify maximum number of TCP connections in the connection pool.

### CODE REVIEW

**Comment by narusemotoki** [comment]
LGTM

**Comment by hayate** [comment]
LGTM

**Comment by hayate** [comment]
@yugui what is the limit of Session connection?

**Comment by yugui** [comment]
@hayate Thank you for your good question.  I confused something, and the PR description was wrong.

The original motivation of this PR is to limit the number of concurrent TCP requests, but this PR itself dose not do it.  This PR just allows users to customize.  And we will customize it in another place in our private repository.

**Comment by hayate** [comment]
@yugui ah got it thank you.

**Pull request merged**
